version: '3.7'

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: psql -U postgres -l
      interval: 10s
      retries: 5
    volumes:
      - ./api/postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - postgres
    restart: always
    healthcheck:
      test: curl --silent --fail localhost:8000/status
      interval: 2s
      timeout: 2s
      retries: 10
    ports:
      - '8080:8080'
